# Generated by Django 4.2.3 on 2023-07-16 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('pclass', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd')], max_length=20)),
                ('sex', models.CharField(choices=[('1', 'male'), ('0', 'female')], max_length=20)),
                ('age', models.IntegerField()),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('embark', models.CharField(choices=[('C', 'Cherbourg'), ('Q', ' Queenstown'), ('S', 'Southampton')], max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
